### ISSUE TITLE
Adding few Frontend resources

### ISSUE THREAD

**Issue by Manish5121** [Zaryab-Programmer/blockchain-developer-career-path#1]
I think we must also add basic frontend resources to learn html css js 
- Assign this to me so i can make this changes

**Comment by mzaryabrafique** [comment]
go head to contribute @Manish5121

**Comment by Utkarshsharma1234** [comment]
Can I also work on this issue.

**Comment by mzaryabrafique** [comment]
Sure @Utkarshsharma1234

**Comment by Utkarshsharma1234** [comment]
Do I need to put my name before I am uploading the courses

**Comment by mzaryabrafique** [comment]
@Utkarshsharma1234 you have to add the pull the request, I will merge it main after check
